### ISSUE TITLE
Improve popuponhover.html

### ISSUE THREAD

**Issue by hhkaos** [esrinederland/CoolMaps#2]
Hi @mvanhulzen, I just wanted to let you know I have been working with the ArcGIS API for JS team to build a sample app similar to [your app](https://github.com/esrinederland/CoolMaps/blob/master/PopupOnHover/popuponhover.html) (for [DevSummit Europe](https://esridevsummit.github.io/arcgis-platform-an-introduction-for-developers/arcgis.html)) to show a hover behaviour and I think you might be interested on this approach.

On this case we are using a layers created using a 47MB GeoJSON to show performance enhancements vs a [regular app loading raw GeoJSON with leaflet](https://esridevsummit.github.io/arcgis-platform-an-introduction-for-developers/leaflet.html). So feel free to reuse and modify it if you want 😉 

Cheers!

**Comment by mvanhulzen** [comment]
Looks nice!! 👍👍Maybe i'll create an updated version :)
